#!/bin/busybox sh

rescue()
{
    echo "Dropping to rescue shell"
    /bin/busybox sh
    exit
}

try()
{
    echo "$1"
    eval "$2" || { echo "fail: $3"; rescue; }
    echo "ok"
}

checkedmp()
{
    try "Attempting to load module $1..." "modprobe $1" "can't find $1 module"
}

trymount()
{
    OARG=""
    if [ -n "$4" ]
    then
        OARG="-o $4"
    fi
    mkdir -p "$3"
    try "Mounting $3..." "mount ${OARG} -t $1 $2 $3" "cannot mount $3"
}

trymount devtmpfs none /dev
trymount proc none /proc
trymount sysfs none /sys

echo "Loading drivers..."
for i in $(grep MODALIAS /sys/bus/*/devices/*/uevent | cut -d = -f 2 | sort | uniq)
    do modprobe "$i" 2>/dev/null
done
checkedmp loop
checkedmp zram
checkedmp squashfs
checkedmp overlay
checkedmp cdrom
checkedmp sr_mod
checkedmp isofs
echo "done"

try "Making new root dirs... " "mkdir -p /mnt/zram && mkdir -p /mnt/cdrom && mkdir -p /mnt/squash && mkdir -p /mnt/newroot"

TOTAL_MEM="$(echo $(grep MemTotal /proc/meminfo) | cut -f 2 -d ' ')"
if [ -z "${TOTAL_MEM}" ]
then
    echo "Cannot determine memory size"
    TOTAL_MEM="65536"
fi
ZRAM_SIZE="$(expr "${TOTAL_MEM}" '*' '2')K"
ZRAM_MAX_MEM="$(expr "${TOTAL_MEM}" '-' "$(expr "${TOTAL_MEM}" '/' '20')")K"
ZRAM_DEV="zram0"

try "Setting ${ZRAM_DEV} size to ${ZRAM_SIZE}..." "echo ${ZRAM_SIZE} > /sys/block/${ZRAM_DEV}/disksize" "couldn't set ${ZRAM_DEV} size"
try "Setting ${ZRAM_DEV} max mem to ${ZRAM_MAX_MEM}..." "echo ${ZRAM_MAX_MEM} > /sys/block/${ZRAM_DEV}/mem_limit" "couldn't size ${ZRAM_DEV} max mem"
try "Creating fs on ${ZRAM_DEV}..." "mkfs.ext2 -b 4096 /dev/${ZRAM_DEV}" "couldn't create file system on ${ZRAM_DEV}"
trymount ext2 "/dev/${ZRAM_DEV}" "/mnt/zram"
try "Creating zram upper/work dirs..." "mkdir -p /mnt/zram/upper && mkdir -p /mnt/zram/work" "couldn't create upper/work dirs"
CDROM="sr0"
trymount iso9660 "/dev/${CDROM}" "/mnt/cdrom" ro
trymount squashfs "/mnt/cdrom/root.sfs" "/mnt/squash" "ro,loop"
trymount overlay overlay "/mnt/newroot" "ro,loop,lowerdir=/mnt/squash,upperdir=/mnt/zram/upper,workdir=/mnt/zram/work"
try "Switching root..." "exec switch_root /mnt/newroot /sbin/init" "couldn't switch root"

